#!/usr/bin/env python3

"""
The check.py script verifies the correctness of the files generated by generate.py: the CSV file and the modified FASTA file. 
The script checks the generated SVs recorded in the CSV and uses indices to compare fragments of the reference sequence against the modified sequence.
"""

import sys
import csv
from typing import Dict, List, Optional

def read_fasta(path: str) -> Dict[str, str]:
    """
    Function for loading a FASTA file with multiple sequences.
    """
    seqs: Dict[str, List[str]] = {}
    header: Optional[str] = None

    with open(path, "r", encoding="utf-8") as fh:
        for line in fh:
            line = line.rstrip()
            if not line:
                continue
            if line.startswith(">"):
                header = line[1:].split()[0]
                if header in seqs:
                    raise ValueError(f"Duplicate FASTA record: {header}")
                seqs[header] = []
            else:
                if header is None:
                    raise ValueError("A FASTA file should start with a header line beginning with >")
                seqs[header].append(line.upper())

    return {h: "".join(frags) for h, frags in seqs.items()}

MAX_PRINT = 60
CTX = 30

def preview(seq: str) -> str:
    """
    Function for shortening the sequence preview in logs.
    """
    if len(seq) <= MAX_PRINT:
        return seq
    half = MAX_PRINT // 2
    return f"{seq[:half]}…{seq[-half:]}"

_COMP = str.maketrans("ACGTNacgtn", "TGCANtgcan")

def reverse(seq: str) -> str:
    """Reverse only (zostawione dla kompatybilności)."""
    return seq[::-1]

def revcomp(seq: str) -> str:
    """Reverse-complement."""
    return seq.translate(_COMP)[::-1]


def check_translocation_interchr(ref: str, res: str, s_ref: int, e_ref: int, s_mut: int, e_mut: int) -> bool:
    """
    Function for validating the correctness of an interchromosomal translocation.
    """
    frag_ref = ref[s_ref:e_ref]
    frag_res = res[s_mut:e_mut]
    ok = frag_res == frag_ref
    if not ok:
        print(f"[TRL-INTERCHR][FAIL] Ref({s_ref}:{e_ref}) ({preview(frag_ref)}) -> Res({s_mut}:{e_mut}) ({preview(frag_res)})")
    return ok

def check_inversion(ref: str, res: str, s_ref: int, e_ref: int, s_mut: int, e_mut: int) -> bool:
    """
    Function for validating the correctness of an inversion.
    """
    frag_ref = ref[s_ref:e_ref]
    frag_res = res[s_mut:e_mut]
    ok = frag_res == revcomp(frag_ref)

    if not ok:
        print(f"[INV][FAIL] Ref({s_ref}:{e_ref}) -> Res({s_mut}:{e_mut})")
        print("  ref:", preview(frag_ref))
        print("  res:", preview(frag_res))
    return ok

def check_duplication(ref: str, res: str, s_ref: int, e_ref: int, s_mut: int, e_mut: int) -> bool:
    """
    Function for validating the correctness of a tandem duplication.
    """
    length = (e_mut - s_mut) // 2
    first, second = res[s_mut:s_mut + length], res[s_mut + length:s_mut + 2 * length]
    ok = first == second
    if not ok:
        print(f"[DUP][FAIL] Ref({s_ref}:{e_ref}) -> Res({s_mut}:{e_mut})")
        print("  res1:", preview(first))
        print("  res2:", preview(second))
    return ok

def check_translocation(ref: str, res: str, s_ref: int, e_ref: int, s_mut: int, e_mut: int) -> bool:
    """
    Function for validating the correctness of an intrachromosomal translocation.
    """
    frag_ref = ref[s_ref:e_ref]
    frag_res = res[s_mut:e_mut]
    ok = frag_res == frag_ref
    if not ok:
        print(f"[TRL][FAIL] Ref({s_ref}:{e_ref}) -> Res({s_mut}:{e_mut})")
        print("  ref:", preview(frag_ref))
        print("  res:", preview(frag_res))
    return ok

def check_inv_translocation(ref: str, res: str, s_ref: int, e_ref: int, s_mut: int, e_mut: int) -> bool:
    """
    Function for validating the correctness of an inverted intrachromosomal translocation.
    """
    frag_ref = ref[s_ref:e_ref]
    frag_res = res[s_mut:e_mut]
    ok = frag_res == revcomp(frag_ref)
    if not ok:
        print(f"[INV-TRL][FAIL] Ref({s_ref}:{e_ref}) -> Res({s_mut}:{e_mut})")
        print("  ref:", preview(frag_ref))
        print("  res:", preview(frag_res))
    return ok

def check_translocation_interchr_inv(ref: str, res: str, s_ref: int, e_ref: int, s_mut: int, e_mut: int) -> bool:
    """
    Function for validating the correctness of an inverted interchromosomal translocation.
    """
    frag_ref = ref[s_ref:e_ref]
    frag_res = res[s_mut:e_mut]
    ok = frag_res == revcomp(frag_ref)
    if not ok:
        print(f"[TRL-INTERCHR-INV][FAIL] Ref({s_ref}:{e_ref}) ({preview(frag_ref)}) -> Res({s_mut}:{e_mut}) ({preview(frag_res)})")
    return ok

def check_deletion(ref: str, res: str, s_ref: int, e_ref: int, s_mut: int, e_mut: int) -> bool:
    """
    Function for validating the correctness of a deletion.
    """
    if e_mut != s_mut:
        print(f"[DEL][FAIL] Expected empty mutated span, got Res({s_mut}:{e_mut})")
        return False

    left_ref  = ref[max(0, s_ref-CTX):s_ref]
    right_ref = ref[e_ref:e_ref+CTX]
    left_res  = res[max(0, s_mut-CTX):s_mut]
    right_res = res[e_mut:e_mut+CTX]

    ok = (left_ref == left_res) and (right_ref == right_res)
    if not ok:
        print(f"[DEL][FAIL] Ref({s_ref}:{e_ref}) -> junction at Res({s_mut})")
        print("  ref_L:", preview(left_ref))
        print("  res_L:", preview(left_res))
        print("  ref_R:", preview(right_ref))
        print("  res_R:", preview(right_res))
    return ok

def check_insertion(ref: str, res: str, s_ref: int, e_ref: int, s_mut: int, e_mut: int) -> bool:
    """
    Function for validating the correctness of an insertion.
    """
    if e_ref != s_ref:
        print(f"[INS][FAIL] Expected zero-length reference span, got Ref({s_ref}:{e_ref})")
        return False

    left_ref  = ref[max(0, s_ref-CTX):s_ref]
    right_ref = ref[e_ref:e_ref+CTX]
    left_res  = res[max(0, s_mut-CTX):s_mut]
    right_res = res[e_mut:e_mut+CTX]

    ok = (left_ref == left_res) and (right_ref == right_res)
    if not ok:
        print(f"[INS][FAIL] Insert at Ref({s_ref}) -> Res({s_mut}:{e_mut})")
        print("  ref_L:", preview(left_ref))
        print("  res_L:", preview(left_res))
        print("  ref_R:", preview(right_ref))
        print("  res_R:", preview(right_res))
    return ok

def main() -> None:
    if len(sys.argv) != 4:
        sys.exit(
            "Usage: python3 check_sv_chr_split.py reference.fasta result.fasta result.csv"
        )

    ref_dict = read_fasta(sys.argv[1])
    res_dict = read_fasta(sys.argv[2])

    total = 0
    ok_count = 0

    with open(sys.argv[3], newline="", encoding="utf-8") as csvfile:
        for total, row in enumerate(csv.DictReader(csvfile), 1):
            chrom_ref: Optional[str] = row.get("chr_ref") or row.get("chr")
            chrom_mut: Optional[str] = row.get("chr_mut") or row.get("chr")

            if chrom_ref is None or chrom_mut is None:
                print(f"[ERROR] Missing chr_ref/chr_mut column in row {total}")
                continue

            try:
                sv_type = row["type"].upper()
                s_ref, e_ref = int(row["start_ref"]), int(row["end_ref"])
                s_mut, e_mut = int(row["start_mut"]), int(row["end_mut"])
                ref_seq = ref_dict[chrom_ref]
                res_seq = res_dict[chrom_mut]
            except KeyError as err:
                print(f"[ERROR] No data for {chrom_ref}/{chrom_mut}: {err}")
                continue

            if sv_type == "INVERSION":
                ok = check_inversion(ref_seq, res_seq, s_ref, e_ref, s_mut, e_mut)
            elif sv_type == "DUPLICATION":
                ok = check_duplication(ref_seq, res_seq, s_ref, e_ref, s_mut, e_mut)
            elif sv_type == "TRANSLOCATION":
                ok = check_translocation(ref_seq, res_seq, s_ref, e_ref, s_mut, e_mut)
            elif sv_type in {"TRANSLOCATION_INTERCHR", "TRL-INTERCHR", "INTERCHR-TRL"}:
                ok = check_translocation_interchr(ref_seq, res_seq, s_ref, e_ref, s_mut, e_mut)
            elif sv_type in {"TRANSLOCATION_INTERCHR_INV", "TRL-INTERCHR-INV", "INTERCHR-TRL-INV"}:
                ok = check_translocation_interchr_inv(ref_seq, res_seq, s_ref, e_ref, s_mut, e_mut)
            elif sv_type in {"INV_TRANSLOCATION", "INV-TRL", "INVTRL"}:
                ok = check_inv_translocation(ref_seq, res_seq, s_ref, e_ref, s_mut, e_mut)
            elif sv_type in {"DELETION", "DEL"}:
                ok = check_deletion(ref_seq, res_seq, s_ref, e_ref, s_mut, e_mut)
            elif sv_type in {"INSERTION", "INS"}:
                ok = check_insertion(ref_seq, res_seq, s_ref, e_ref, s_mut, e_mut)
            else:
                print(f"[WARN] Unknown SV type: {sv_type}")
                ok = False

            if ok:
                ok_count += 1

    print(
        f"\n=== SUMMARY ===\nTotal SV processed: {total}\nCorrectly validated: {ok_count}\n"
    )

    if ok_count != total:
        sys.exit(1)
    sys.exit(0)

if __name__ == "__main__":
    main()
